apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
spec:
  template:
    metadata:
      name:  init-db
      labels:
        app: init-postgresdb
    spec:
      containers:
      - image: "docker.io/postgres:13.3"
        name: init-db
        command: ["createdb"]
        env:
          - name: PGPASSWORD
            valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: storage-secrets
          - name: PGUSER
            valueFrom:
                secretKeyRef:  
                  key: POSTGRES_USER
                  name: storage-secrets  
          - name: PGHOST
            valueFrom:
                secretKeyRef:  
                  key: POSTGRES_HOST
                  name: storage-secrets  
          - name: PGDATABASE
            value: bentoml
      imagePullSecrets:
        - name: regcred
      restartPolicy: OnFailure

