apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- regcred.yaml
- authsecrets.yaml
- yatai.yaml
- voila.yaml
- github.com/alvarogg777/helm-mlflow//manifests/mlflow.yaml?ref=patch-1.19.0
- github.com/alvarogg777/superset//helm/superset/manifests/superset.yaml?ref=patch-1.2
patchesStrategicMerge:
- patch-yatai.yaml
namespace: ml

