apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- regcred.yaml
- authsecrets.yaml
- rapids.yaml
- mlflow.yaml
- superset.yaml
- selenium-grid.yaml
patchesStrategicMerge:
- patch-yatai.yaml
namespace: ml

