apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- regcred.yaml
- authsecrets.yaml
#- rapids.yaml
- mlflow.yaml
- superset.yaml
- selenium-grid.yaml
#- yatai.yaml
# - voila.yaml
#patchesStrategicMerge:
#- patch-rapids.yaml
namespace: ml

