apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- regcred.yaml
- storage-secrets.yaml
# - yatai.yaml
- voila.yaml
- mlflow.yaml
#- github.com/alvarogg777/helm-mlflow//manifests?ref=patch-1.19.0
# - https://raw.githubusercontent.com/alvarogg777/superset/patch-1.2/helm/superset/manifests/superset.yaml # - github.com/alvarogg777/superset//helm/superset/manifests?ref=patch-1.2
#patchesStrategicMerge:
#- patch-yatai.yaml
namespace: ml

