apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- regcred.yaml
- authsecrets.yaml
- yatai.yaml
# - https://raw.githubusercontent.com/alvarogg777/helm-mlflow/patch-1.13.1/manifests/mlflow.yaml
patchesStrategicMerge:
- patch-yatai.yaml
namespace: ml-system

