apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgAJALtdlT5G3Y9YWEswX6cxPRqFDpyGOoBnzRzL+pYn1OII5loTmvMV18Y7h+fTKUMHlovyRaiJS7oK9dJ5zpCSHpNNaquDRSjVSBUcRfdw0D5ldJcOnke9rk4JZZ2SPQXpjsZkyO5bKHxrWJIMJHWZXrpq3BKvsBBnvRCgi3AjVndyhvZhhfRUsE5/aZd+4cXPciDKv/WcqvT0eFz09hMoGk8c8c+d6/9eMDwUS7u2g90H3tpXNto/FmPx/ItRQsRxOj2R/zULkUQWJBBIRoLghzICyi6jHruIjCv8q/YKooUoXhBwMsRI0O0ijZQv17zlIMbDzsA/I211flk62SgXMrXOKVTQA377JL8zc/Sp8mNXEw9DzUIo6kUaXuvKcCffp2LAXB52vmKZzB5G56ganaOx69foW3vCAkCQMI/XwRQRBOjo2E0vXDdRwJL5lsepwI6IpOo2ToIhW2XAXTfaMzes9qZBLowPgzM/PHzhc7NPCZBGjKM9UyhjtIlR0IUG4+YXkoaq2Y5FZ+CRpyLg3yqDflur9Qf2xalTJrV0+oZsa5pAvg8vVZlQxvYBnxZCujcdl/5PBIqC/fAK7yZsaPoBzcfFHwBHz0sz5KBmC5o1RxkxiLtYEIzuT3VKZJuo8ZjKCut8qg1q+ZE38kDPhIbRXBLfB6C5vicPsk4k0RTWKPasbOSuaxRTq1HYzJUO7+9NwHknMQ2Q2wYB0tO/vo8doFekCUPRGoFpP5QEzJ4gh+QLixuyQxp1bRSRupzKd2MitFVRW64t7uCeYpimGSf73ZnGz/V7d+igqAcAOn2Z7dBnWSI7qkNOnUYXaIEZk6KPcqf9c1DWeh9u/A3gj50z51KFdGgi2l7d6dnyX38L1LI+ffQlYnk4d+RKIHOLIoPLSisLZkKYAhXV9QmzYI80BGKV
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

