apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgCeUTS2NGuTR0cA1YFXwxa3Qen0pkL1g5gGGsC3ujhMqLJQJ5M49raSlmAUelaSxWo/Vy1OU/bBUj1uxRmVlte5KdBltcyjClR6/ZW/XXf6TxVafotR923yxIzHUkcHEs/q7fzyvvgXWJBJxaPePDJtbR8RW+ZrESaSMljiqqW6DkmIw5mMAlUI1rchc0MDImgnDM8x1NVahHgjXT8sAitt+uMe+pS7G4P/FLB+cy2xTnfPz/HA+YELAGnMnM0ys2Uv2UZhlLcQKCBQijN+Nv3HX6TUV2pR64hCWnDPGB92xZXxRaLxO8jX7d3/F6aRwVwoNJKfInQzAM1s+hr1NB0MLOhOSOO+Ia6778iWyCjZPlxhJOSoPjEEQE+tmekxRRxD9KaViB9hXOgJjD2Qab8EP5a793jwHML2Toeg02pmqiBfuLYyhbM+4u+dfRQSOtn+MrhjDQR3dPv1nDdC9hcPlQnunC3kXjNX0aAFa9c0oNHoklKw/ijsQ+G/IEbCVkMydJrj/Qfi94NNseLFsRKfGuv4xreHCMi57DijWAincXOjIrJ4N6a0BTpkh3pQD4qQnqL486fmzA2sTH5YSAFr8aVo6wsap/Q2HcdTbf2S6EZouc+/9eMCi7LgA7rQddgMx2nfnuXAb+cIakYAro5TVdX0J9Uj+Ba6fxjusiowj3rxmRvVMFtagUtvEvfRt1085kw1WqYlgUz7nxQUvARDzaIlYvKAAgRc5qrEU3VcDp6y9j3IbzBUZ0EYSiZANDprUm38M9xrMLI8TOxem0JqgDrGfIhR/QtW+kUC21cJO0R3lhxkvAcZYVvORutXaCPSBJL4WxulYYyLp/goJp9gVuvd7WIwCDjxXFCGdRv2/iv9I6MqMyLqfkaZXBhGrajN1tNXTzLVPuPmsQS3QO5RXPxKr8fo
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

