apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgBTPxC9JbRRfnaLbk8HTvcyOFUkkyraBtDcGoXmB6qCRhg+8aQY5p3Iv5vLdQnuNYWEZI1DBLW4vI3ntRGN1UCr3raiHtBHbl1dfq6rEoFl/A6/VXyjRfQ6u2hb0YhKjF/bFLG9k52+jXr32GljFvAg43UTO45U2z6vWsTt0Usvx7s/xgL/GXFmNF0ULTBwunj8X1KfehCyQyHLEZ6eE85sAP+1PlpGQTFGqoKtCm+uNx+p388gXxMuVmk/mtKYa+fMARUch6TtY+bqJ4U8gX5jgNpqFLecWPK5W1cdBR6D+3itNXfmRuvswDzD7tBLXEpgqQDWbWvDokllAG0D5B1eQFb8ZN94ZlRoCt7S182hgb6wJSgm7XiG52xLzMdaO99T3oG5zl4tokk6zCISU+Z5PMsbzbkImnaJWZWIUH8G1EOKPjq9aI1plWUIYUZ/HYVte2ptkOajZyGy+F7XZWXGfZFuwRoWQB03/2ApKLXH+KFo1shQ7v1sMLTHbFwSJIM9pAPfKcNLHYK2US2+T6XLkVvQFgjgV98ESJf6VPeOZYgfT/OirgqMSVyO+4qSA1U3dojQK1vOIGany6cQB8lhqZTNRTgIeouWxYut2ntcuwpGeNGaa6jsVYg5bSTnlhSLi98zSdKUEYwV74+12g9VcTOGhYtsNla3u4w+iJ17w38QeqTYoCBut9fG5h2G9Lkcs3XYT0lvGHvnP/10tcmk4SzcyhuFOw12QDU/2wEX1RCVfsFc67VFHJaAiqtyfIoD39++scxWu4Xgs5TYjpLX8c3vr2Bla2X28NrWM8VlwVGDwRJ1ocyjPKPRiXe9csQns0r8Z93RylT/oTBUVfaexM5Qd3HSkGN7ClL6UipHArN2man3zGZSRUXeVF+a8/gMe46zn3d+GaKSVPaBulefhddR8YaX
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

