apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgBLZsN9jEqDweFKVuBoOzK1BtVwI2/I1ZQediSlBcUAEGtDUU8fQ2klq2j1ES8SQ/yvkq6SxSTlAY5Ma5UjXpDCGRlSkNZow9IaaiwqYc1/RpsafBJxS4/Dx65PmGyCVCfgDLjtm0LS/dGNFfcRdNP0U+YK6lpxnyw6cN9SU3B8g3VslIUt65uuuMDnw6rs8SBQy3Lo6nD5vttw+hHSFIvZLukDEPhp8Th3THUZX30e6SNZS7Ic+xJB9IxTNgyeLonIeYm5FudivmyM2zeD8RZ6N6fpzNWQawzroJ0D0GaZof6KV3DZ6cu/3bedyJ3KfmoEu8J1np3hoc8t1ms/GnP7HTcIQKHefqmgP6oI2DOg7fT+ZggowHPDMIqEeBN5IGqTOWVwOEK++WP1gp8k8U/vw3IduR1Z27CuWT5ZySryYdR9KZ10YyXtXPNUbYye4KM7Wtes5nsfHMdyGXr7DaXfkBrXgRRIQ893HLgvfWE2VIfJw53iAx1D+dJqYM6rr5sNvjUTu6IbfzB9smQJgYFIO5Pqo/gwkqRKMi/ZGCAQBJwA7RPrA2nZ7VBdxCIGEP/TsEf7iE71sBBWGzHPGG10FkTIh8Nv7sWqjXSHs/7cKmm9NIB5qJF+i+ka0atRNC9XtHK6pCYvGLd0b8lWSKtXb9IcEkt4ZKAWkhcM35nafk9roBP05+Sc2HrWDRMRr4zztP5WsD8fVxbO1WyQUy2BWNSQT1mVTHuDP7kdmHcj5aIh1xLeBg3x7IF7/M8SOmUFWVULRcx9OQt9G00ceJZ/tjL4yCuOrEzK0zYMFLF5eN7hIbZcZfK+wWMIO0xcqAttw6IQ4FbyGQdQcxCn5UkP53kBKL9QZ/0tiw2KqbyHLmUfStQdDgde/TFYL665AMqO+5kk/Mr4gheplMKVYezOgwapdUv9
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

