apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgAFdRt3GCHtSe34fvFqfpZlARFD+091g/XpFSXC7z6ubxtORqx/vmwdTULCZoGRlSvOVkyzyYyxD5DZGnTwWn34MvcNhU23hTs9FWwMBD+WjaCuNgVKvI7cY3P04HyroJx4+Dxf1hcqTTamt2dTm+iKfTd9IUAbjfkFKtg8myB4hFRFzK3g6780CZUrsFlA4WEDvJicOS1efsONcL7V4Ss2EHPq+3nHI11RLVX1raKXhZ6F1PpB14IeI51sH/hMuhd3Q7XwFBzsKg96gcj6eRz8ucvC0OTm4nB/zNEiU5YLE4KSoi9iM2s05Y/CfuXs1CGArbwQuDXpXgVOiw0FR1kvkQV2x0r31RjBc08LUO5eCxysMj7oSR9mfMej5jSzWJ7YctaCFM+KjMOt0SKDN41H1bKOEVYbtMtQLzHAIC4/tOWcIhwy5eanLY1UL0UhVb1+5yRGlCMfNlGfPrcEE+XuHSdRW+YP8PcE337y+q2YMEWduBnQ9S/PrALTpngg+oUm6w3S+hVvl1CUo0LClEMrp1GdyAhKApj9opBthVn94dyLKhvjuQ/Jw/LH+7+KTSdI6Eosh9YG1GcAOrcdCf20D+0zgUPelYJM9PoNrALQZ3FXU0hIQoQ9wK+TiIA8WsFeJ1xqTR9uWK4VSn+3NUW5ekQJqA1tdaVfyBgva2V1/tSeHRnuGg/cuRrj+ghOhcstdcuLJzyPvL61SeBJGY7NNTmd57Cg6mwr+IitVt2g+wh9EW1d1RaKwPuS0iFDnLB72SoQ7ixfxQ/8dDigVU61jChRN1x5GSYZax82AEfUal7012N+/qfffYqxQLwXgZzYVKfG8mtBqpCjzXQX6o7rr0yakb4lYBVYc59t66F8GDsUB2hN8mS05WjOp04PNEXI+Kj7G5MhejZzEwWepP9iuOeYjHPE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

