apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgDgsOPVreBMyTMxrEr6/YOsNOgZ74UR3Q6gJnNIKhh1hzkgiCxNw/lk/c6qAWNgMOK7U7cYq8Apv+CQ79UEuVtNVCQiLpM73DXZqqYiIppMHSidG4zhOYe7ekGgLFEnHVjeRT8PqvKCbQ47OgjFTRbyR31e4+I3M6aBsHcmnmlKne6RJvjRDRWuoamVdznlHHQt1mb9IRfn6YJ/43O5AI8ELhzHYOwHtbvhcGMvCSkNlCNyD2hKTm4CSG3HtXoNiU0g4wgG8XH2185plELuW+GUFOk+IkkPo0p234bNnpos4BvuZpB+pNMnscgPMAmPvrfQypvvgnSqrjvGp1Yf+vwej6moHY7GYtjm4U4RpwYJOZlduBp2PWpDG/mtIY/93BoRUoPUfFLMS3MkooV6O41jfxAlgkp0JuAaRMUbjFZ1Dh2vIA7HBfHvis2VXWYEQVCb4sKCjzi2JRiQlULvwu7kf8ewfMRKd1oU7ouujm9y936dmHm2YZdF1tFrnYH8oZY0YmTIa+ycRvQpMbmLJNGFbJr6qqgZaCevJ76WE11Zrw7UvwlvnmURxC/4+pkiZQS368QrgYB0J5OVyhCK6L85urYn/yaUtADFS1Sig/bk1lg6vxex2kb1/1L1bID5hWwrPNK/yod3Kf0LdcfnImzMnZAGVqToh7KCYdxGPdHQRRNuj5YJjDkttUc0rLEjqiBWZhB/eWu8JPHGrwCyT9Hf1OCzcIqEwCoDbUW5h4X+yB5ob3Scf2S5xV1H/wBEYCG/I90hNmhJXK4+4yXBVJBlB74LOQqzEWER7b9IYVUIPhGTzVzLn/5muSopOSPr4gn5b/tZmjxprxWbMNdfPnro23E0t1pB1tpHrc80NYwqOld/nRbjmlE59kpFlaoqpEIWLYqckwEN58YWwzxTMxK47e2Htr2z
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

