apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgALQms5tHFv0nkKL9GgE/o+dauhQkZY8xHEyK3EpTmyWciONVy+VRLcNQ6m0bAqIWgQdz6DdAqzZTJEapK7PKgviWs8Sh3Oqtgu5N+8yXBKVV1x6Tf8JB1HxnikCvJN9JSN6TtVF17NL+kDt41rBEcToeg6UPyylfqtjQr/3GcEeGrJ4ec9HpSGvcoVTNKMTbXeOjfroc36DZr8tOweot3quzVTCxUOez65IrKNUhgwIhcAkqYhufKSWsWJcTc5dOHL++uLp+t1ULjo6qOSBoNpmraQqh5q2BaCqb8GduQur7xWnCQB6tTZrS0jMjipJ7KxQg/Xk+9fQOkJtapsc3dquVu5MJLl3Om75OwpA+Ubi7k9tvbd+QAqCzxPu0SIoqVAaoPsqzCneuq2LJ+IyGFOZi890t5REureImZImJ1NpYW3ZercqPZprp+CMoIo8aAnjptJZjPpYAgZlvpzC43W/kvDA5KGnwS5dZ3O3SVKFcdg3mnMk3Ulu3xebkr7dAPr8PiJxM4Haw2KHlHO9VK83dooxV7FmS0q9a+XnuKOJSxmIaF4xV4ZOe0JNdjTtw6l2U+6emA70XxEnbzHMfowuI4UlvO639aflVIR4CZfHKsO9HSFzPFKFl8ztodBHIt2GrPbL3zlfDCHIOXsp+nqBWGTUyEINQaD85bhdUg/WOsSt11IOmue/tK+B/j0j7XlxonSZIvd0YaR63qZQKzDnTbPOkliV3Gn5HNvlVOCA/WlTuuGTd5ZJQFXqqXdlHIjY71Jp5Idnvb6ki3q6s/SBWOr6fGqaR19OzUg3WL0KCHae8YPMrnJpIyKIYTWt3KOJtVz6sSdfeOM3mi4wwbnY974h+zq5g7dh7vz3Ud42RU6k0XdgDXCmX2cnONL1kl/uVDUfebpiQI5hZI4CJgroN7eMuGK
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

