apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml-system
spec:
  encryptedData:
    .dockerconfigjson: AgAUqdU7wY2DK7ODv9DSx0i+LoHM2uvFFv3h0VOhTQM36Irt8bf1WjxH/ncPVGGNgLh0a6BOlxIYneJx4BNI9pm+gyb4eLKhe/9pAghxUy18Q7M8X/hVrUKDytGH+DhpJlNNMtCQgkl0lWZcuE6pCBkBrCcvxTJAg7jyTjoGRBC1frJ+owb+JloGAGA69OLvFm4wYHuwYiBkBq4xPiRnkFjaB9Y1zQUF6ouIgml6iPCCFQn3OPPqTLTsVEvvCAnwTuuqGvSA6LGQOburbeQa9PEIA2XzkJerQLxAGOlw4lS7BF7wt9inx1Vz1P9VkiJS79X/HrWTlAllxup5lAOnimXIBTCsxu1mFbiFqtK/u58P7QLDv0hXH6ls8Ibk+pj01u4cKzoQ3lwYHdp+mnEbfWZCNjCXpZwI8FmsOuoWhuZfqwOpnC7VynYeTT8H4fUWENrZtb79ClQAbaoouLtzzisqNZB/KCw0a4RrnADaaOYe0iZG7Y7wcpSq+5NfgvkUaAfeKoyrkWoXkCW+vpLF34cR6vyHaqaCqi9ckDR9V/jSP5DqnuVGgqGgEZzpBM+6prTEnd9a+URjn4irxaw4ORpvbrr+qyfi2A2bkBQCHb9HUTCiRMsl5EeCe0mLtrQa14qWsgmZuAhHFbePiFOVUVcFBggjSSFsq2T+JD/BKBUbLc9q7WkJoO/4GFluCmx8O3/4SjqN6RLtZGCVsvVElctJjVLMTmDYbz/F3lqJ5P53zDXyVYGtU5qiUFSWCzwixeTmth+qWQmEL3NSTnxi+U4zGjKMlioq4dBcX7cDB/k44PSvCTFMTvByhuzpJ9QSCo1dEItgdSnIxWfBTkgJsK77ba0rgtL6E/+Qp9o5fOO0gWwH2qf3Knz25/b5BPNxbe7zlI6oaxZnUR5RcIIVAH7ehy5RN6px
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml-system
    type: kubernetes.io/dockerconfigjson

