apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgB/YgIaqOWN64PNlmuFjXYZkN/vsKO11i+pQiXXNN8f+5Eg0yf0flQEcrdUixhJiUM+AaYhDH+YZKnJtH4N9F1AD14R4ZoRpNS+Q820Rcdd+OR/ALoUxWXDGQenKrfriknzpLp/rJgNQY0zoDpuVQUCY07oDI3ypZ5UUb0pqJm/Ymes2h0e5JzQE8VQasNABH36SpK2mGR1P9NwhimcVp7Q/BVF3qphKDPEQ05UmcK89AJfps7gqvipJGWXb+2xH/+g9sv5dZ5nZ/a7ZwdY+2+pQnM+5w9urI4+7LTJnw30Gi0km7h+fDjlk1ruDrx0P0uwWsRztL5iK0aJacmkvG2GtaPxBmv5UwfbCWU6/q3JHktgUzULhLQMuMQPV6EZxEieYSIHSo+1but6YPDW0lGq2NiXGloi2mZ70VXjJWwSqWXo3yOEZemPxAFCBljnrIhtnRSvrSIATEdGA4Fn4GD3QWTSNNVVmSTK1VnN8X5aopgJMPfIuc2Q2cSfSy4xVSDm9ad1AlHXYgsgbBgH0wwi3PihWVg3PAshUKgOwRxzn2ohrSIibiF5BjZD+SS8GwYJx8JBZnIfC03ZOdpS+C8SDdvTjK6pTG5Q0T5qqPqvGyv6aoJKnj6mmwg07K0jnw/HUvYZIUPEm3z9wS+uz6odos2pJXwWKKzXDdy9CTvJQA5UmloEhnalz3MgUKxwdWOWqi4yP6F8FcVfkGNNrTg+h//ctZ1g4wC+l0uXMJKWTZWA4d0QcYP4JasWVtX+9U4DUR40cqJ9Dt+RFD4XxHgScgYwVV6xRSdxGXI8ac7MKl7KVCaONPbqy+ycWHbRHjT3mUUIENoE17+12galYExAxJlqcbCUZWWcmusfceFj1l5aLri74ic1rQON81tx4BJy5rxvC3IBIU/Oxg5Z2MFC5QgOzOXC
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

