apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgAQVT/HtkRpwSCk9ylZKVIS7GsQNE7uJvKZx7JTUliDUcjeVA4STfCahhy8gyCUx6tYOTRVpFv18HLwPQK03OEvKIPSZfaZ+QCt0HIJVuz46EJap2Go+M/qXCCOF0o9PFw5DFhrneQcge9pe2YOwM/4I/W6HJL58Vbx4h02C34iTC1c+R+sKiDDyHl7OPMQh0vMuHE0HMXplLXqHxejtNn4NFs/zQ/1jl5vKD6zXT8EKFrmzRfuwVOCpYD5dUGZx5BtmvkQO7WM/6QmhYCiSBUdbN47tKpG5+2wRD8zU40MjatKg8VCGcyDQaK1U89CLmDTLRne8JuFdf6Pl4DUC+wUUUkPhHqX4nul7GZgIVAjq/pUm4mN1i+GVUgHjBc/fOF1o40Fy4mp2Uf7IGpNbB590FpYIgDYOqFzB6x3v9w7ZFaRMZFDcQY41EeQRbunE5c4BoNtxYibkqC7QnK1uvaeSg7nnOr+CO5ig9/S3jsxCJMkCjEx/OclN6h6TXDmWH8IFWU9Wbt6CEQW10b5E+DY3wkpGHoEVlgplMpZqWcmrOWmDWUCc6+n03LcP37LfS6lM56IPKat7zQG1gTc4M/89Q6RM/9sXq8mHCcM5XR3W1GWZ+mfql0MFr54qZfgLs+ZKZuzybORkaxpne4ZGcnYPu2LfEaJg9zvlXu4xQUeQhDszOhrltlrXj5pTxUBLyojsJPPW/AY+zoyvZv1ujxjgeE4ufLaohkZxUZPm3lDWHaQjkxExkjsZTIaKBzpLHDSgKnHuA00gy5pl/wMDhZEf/7hgyBABYAqfSymcR2+1NRL4/4bSdrpia+mV7CfF+jGcSntTsRKidqWQh7OYEUAeABgtJogAHFPNXw2CG8kgRk8N4yHxbeo8416s95EBKmpcHrGNmMS0mssfOcpbm751+y/wPjM
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

