apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgB1jQzHGQVF5YXtLQvQC0bidL+GAPuah3ZzFnCH83UrRqzLuRLxKWwl2PwCx7T/C1oLYCRoL4waCQ3tGZGFcoGO7J+IYAL0RrEQ6x38DuvxXgre+LnvmZleE9SMGPUILKMDv/Muu/YrCHikp0HZQ13rWDfdBuHUQlYf7B6qCWF26HuLy6yWrO42/J8y1ZWFWtnrMGK6hkA+PqOum+SmBPp3Yb1CLjMpY99gUXZg2aY6TmBfka/1RzRWlbgVhqpc4V16trlStQQvV8HzaZtKp0PsboVkcLF08FpRZMq75fP4lr3fsE/7doy6kfqYqom1aIR915o3gztsypwZ2lHeEVwT+JzwGoRLmaDE7LbAovP0ypwXnxvlNKPik7mFe245TbzGtmxZd/OJi9foAD9K+yQsPDlTcU+mS5EtVsA023a7blzkJi+cBGWwssIde+/0Pk1yqFvoTqXOowOo9BH4Nh/BkwMVGesvI82+V22oQgcfWLTIvzWxoxXQ1EylKvEZ15Md+r0BF+GXlX8hIOube1r4t5kzcKw4QKM+6LSiycSy/jqxnz+VXfrUabGmXhUEbk8rvBcy3zPRwKr8TklqgcpN/qXYVnfUS91SqivvGuRij1n39N4y/4DEmeKzukZsn/oP7ehF4cig3UGndG/Re+rVBVkreDkHatNGUcp+ShNYu18BUPoeXRWRY3zg4et7iU7+ZiRLcuBTU2kMB6RLKj6SDSpOWU1CIPeFuzENIBF8RqdsUHmHX4jJ7icArJM+oYVHlGHaRnZsC3XRjxubtjL1oDTIYSHBVqL+2a7mV1QFvfX1oO/PNZ1k2Idk8wuccrgnR4WyxMuMeuvQwon65xpepa9MEZr11DX5Kc3FCsxFHJ2riw0AJIK69Fq77AKrD7y3gtaJ+9n9HasIxTIshUZ+t1obpnKa
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

