apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgCfowt6hvilhip/2O61vq2Sfe/01FyvXO+jeW0jLtYPrmqmvPNBC1uC4XoLOkJMqbgpImvO1w1/DUHGYYeistA1hfcUMp6ebHIzKbg5vAC20cO/rZ2dZISnP73MDxZRLx5b1DkBXxK8kEV59dllI9V9dVfNAVJVugcUnhAMA3LGRlj8VJFKc3xyeYNVTF4X9Id3OW0sdG0paUfQ6ukyEka+kjw0RupDaA/DlBSISUHnmnzj7rGrQYfYaZNKnaxm8gUS0DLlQde6JfUQXA8Vr6kdPU1O4aMLZxgM3ARH3aDtSZ9Syo3A/Vfa4hFLcFN/YE93yeJRCt5JAaC2Mnqcj3i1KL8rAEaKIyc/7mg4esNcsIIVrYU68ZlttujXO+PH1xGKiodurxD6Uv+yI+gqtKfSilOM2hs6LX/XuffQDlydZQvBkqODIgFwwJ6Sg9MLnX3VoUL1fEbZSOQFvvY5cukvGjFBS72V563KaT2hY5JupKdGT9QKEGG8DXM96Em0ZoMSec0NGiAOlIMl3GMm+loEQ0tdV7OjpXp3KQ3J4telY/5ifn341yrABzmkY+TLDJud1IqhgGJe7nRnOVvOcrrcg2npSnk2gJ26TyaMrBbO/6vRLr1lLJ4/SJG6lF4MD366ck8k50fv/Uz95fkiD3AcITK17pX2Z5HmNyNjJMBOBW1qlj4KkF03Cr/TS6lUWCMv2cYiI1wWpvao9R2UKLn/LSloVQ+RdF3UxQIgq8INhduvDR29ivYNbxqDxxFKVOp0mY9SBDbt7d+FbBWHIYEHLn29mH/Ilg/8SPyL6wxJWYH3/CqWsBLiDhz2PwmL0yaaLc9UBddMpaf4P22Z57NjEfgjud9TwnD/iuBAgy6f9nRsbDIkaul5ou8zj7Mu3gAiVxwlhjTBHfFBIVkp1Lv1qVSOXAmK
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

