apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgBMDhkXXAi2bW6rWTwq1HlFqQAkpOi6FTyWSoyqQLjCu3GG+Pqybg8d3OynF1wFdpX1AbwyihcoCdOQOa2Pq0ne2zH337GB8/6+OWclNeVieNYA602myUtlpTVAyT176eTO8wF9U3lXumQHGpPz6CvmFXJa4k0/CWrWTL+EihzePS2+AXnJoztaMYbUHaeZOvhHAvxFJflQf2zjC+X6FB+9d/2WNdQVWHKxHtIEtnOp5amPOBCLiDz1+n4oQ8Wai64eDOi0+yDuo0Ocsqs4CJn+CqZvoaHu9z+gPAFySp7DDXGT3IO9L0nPlND3ZguSo6YtZfnfl0icMHo4BbpR2sZghIuKHDqVzuG4tNkjUGAlWIta0JwbHtpnY85Y250nsfEPmIpvNIro6WRVqdm2Sf69/zuqk7ugG1dJBKiDHctD/wlb3Cl6mlnRCxAW6d4hXOnhl3lQrD1ysfkNtgj051sHhfEH2rRo2PyvqCBI8VjO4c78Lkbzal5Zs0ERiMP83Am6o3ENdnAStGpolFszcua+1e4WuFMhEh29iFpWx+3qJ/R+vsyAV7mL1MWHqMJzbKlh/u1tBx5E1Dox2JoB+g30e/MdGhrWfn5qRaLY6Wu+M6bN4HjmD60WhrSFSpajXJTEtDbroPYyMh/BwfjascShb55gaY7WiMOf8VzynVqeQwdj9n3wLa3/tHCJLm00jspCFweQke45tPAQNsL3fw4en+hqT081DRdwFQABn8Gd/RpTHDRM1ftnx7DhdYS78cbshMPLTuy0MVXsXPwMswRNIpWgs8n+mB1MlVWkJxQGd5W/4QQgI53kqcIntGmqQQl+zUER9sgACpWmmLsr1VSa7wVQ2g+uJ/3RyVtK4w0GP8TwDBfE1mPwg+nC/dNd5J/FsJCUwy/NzVrQK4RIvFvei/SHz7x6
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

