apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgApRr50JWQOECwsNjDRHMBQWOJHDbSPJPWrbUXVuTmC2frgfwci4USH2jex9wuzMD4vgQ/R4rAlXK8zAUMkpNez3V9ZMOjJ0U1dqyKVXB7hAih6wu2Jibl+IaQJiB6+aazs8pNNXDnNJfdb/CqPXq4ecG9TNxzK/z0lDyRLUoWdUqebRLSY9WV6VVWmP4X0u2sDWYSRFiY76rB4TgxMZ5Ev4ClQb8ydfOeotNCrUdZkKlPw0D5oxYo/e7qYNNvVzFUAzymg4KkitzfiF/6q6wX8oOVKWNzMSGFqq6bzdQ35MK8PPMQkSAPRcw3Hdb7pQabYILdFTbY8v5izNIvhKfHwvyKUwBqUseipdybzJUDmoMleFYaJhCS/WTsDOsOnH8Nhf/iCCVhREfTlcMp7fPwI3J2Yf1nfUNn1GP2n3PSx2s/zZf8Pl76wHrFewhgvDAf6fr/zTiJepO8VwbLi8jEsWcx99v+QHg0LgrJsjvOZEE4eRYahwKAnpRFeZ9Qfkbe1k0QTMW2gJlVEO9BAFsIntWyai8gjBQXz539T9HVWEP9ByGutPt5OGbbqsUR1tB05swJlVLFoXJVwiT7utrwb9bdEVLVsYRJKWJlvxcxC4ByjJoyS8pD/iVMFDyZvPRYnZpp0y1Uimd5cXEA82FLRv5cp4c21Xlchwv3OpFMZfSRGSuPLM2PvyZI4/HFt3J+Ai3fChMkvANkKEMk9zOTHkfTfTN+iosh8JvjkNPe6KG74ZxjqyFZxCl17HCBtBZ0bdbWOpWp0bN5UlAQ21Icq3DQLvSm16eaXhTlahLFOHVI32QroE05H5ZVflC7FTg3oB4/+Drd92cBd9Qt+m63XkJOajpo8oQ7807GQPP3DSTpaGuv8t1Wnbmt22Kq3bJ69KtjIHkbCkC88AlPADTq8FQstIoYy
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

