apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgDJS9jGKF3PcAmlKBiRiXRi6yGjgbMd6HsuKGeOu6vIgKIfQAC4EylHrSB/g0nTFngtWhmEcr3sFX9P02UIMVaKyC6zQZlL9UFCmdowp5cWyE7MoUH71KYGQeDWB7bM46yecAvm9DrB7PfNMa6MZbWzgMPmA6aKJ7MfEdQTLV/TmOpSGyEG5ewNH9KwRYoFnAbrfPXi7nTdWZURV+rxi0PqkCd/mxXPNdd3w0VD7aiB7ms/HvC/fnjtgTWC4rDV8pWr53jQ3h8ZkJukI2rZCHElN/yOEeNJqBW35bJsmwxHOgS7J6HDE3unqtOMeTPkZmk31r2bOXXQCqDHx1RZXqeh4n7w5SHyybJFE4FL5oJrt4gw+9eBgDRGSykq1wbSjNQZYEJMqGflyM9p1BjNKZS8LQ6ZHoxIK0ykGaoY0TodSTvAkYam6vHjSml5nNKbuH+o1S3TNXgYAD35L0Ckq5NtEEN1IB7ec6rp/fWnX7YhVcdkoBo7sHTKgled1IwCpL0OYPJuRDi5+DNbdQT5EWsEMESbEvJLx6fTi5jtwjgyTu9hM6jGg5cnb/Mvz7tIOJ5Io7ACo5MBRnked0V+nN3ieE8HPDm4RlH8i1EJBGDteUcZhdvhoIlHqHUu6OQLXj9WEEEpenpIUph+jQM7QiKkOTNC6exHZD5hl6A8P0PfvzM1GLzz7jiZDxQv3Nt9wVUFgbE7X9cB1ISJSh2HUF3sHXgKEly/yqKaLMMG/N77kyh9/IH4GeLZwtZL7lKDYaISYPsRQVNvubVLC3DQVdbbhMFa4FDCHQeg5kcdfLxykUvdC4B2LnxkcFc7eirJcklmcRDRbttAfNcZmUUD2BT7vQDeh9UDK3lZdL2t8edTXgD7NJPOOg+xyb9w/YAqLvu4UcTPSpGkL7ov/C4oVxjLntRloW4l
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

