apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgArOyku9AeyiuPjTadvdsreKQj2WMKkdqLJxDgyknQzOF2MAA4YwpJ4jYRIZckJWIlZqvuPRF6jKRhgGFk9kVjBL36AwNGzWTMw194BpvLPqSsfUANisdZqXDDDM0I6EGLuB8yJvm9imnYfn8jAu+kLChldAOCFwBMEaTIrdEdVWBctmlyX/o9Qozc1SN6cAF1LIRx9NDrcB53Tgrk5Xe0lSsnQjMseLjUSaPZhitLKD2ng9JUZyP/Jep1KchvoNwyTEy4KGLVSX+efEraSZMaY3Kn/lcKhzKwvkznNYU4ZTcCrV3urVvQU8jdFOlo430sxviuh/mHVXdKG71n1D/L6xzSHiPga8Z9/ZlcZ6W2CknJZULCZpFbnEqfrvNnKgBZ8n5BiKJhqjMLqQH1KQHRrJ9+CJQ59kXol8wx479OulKGFOLMaL6agyiFNz7twJiLDzsiJQM9hjFIZTP5TjwdL2IsnaJKh5BbNt24jEM0avbYiTzle6RZ5C0fKLu2VzneiLmiH6Kx1YO+0hagVHG8TYxl611TtLMWiyMbH1rVmtY4FPr+uMI1aRx1oNKYknn879jAO71oR+bKC5K5pTfqqD1vHDZ7tfPA+VN8HNZpTbnnzZ3eZp2j/8VlTYrfDVVWC21fZAL0ZUGcp1FQ93so1fprVdeAJckjb86T5mV5Z6w1y6BXNzy2LU27caq9HqOKTqjBZdpEmPcbKpDb+WG15wq4KWC5RuQdnaEH+/xeG/0Ym84hqUm9VzoP8UUPOEH+WIUOcGuIO3QLOPUxhaRytu8xQ6yoGqp0FjD93Mteq9AgnCaVZwlc2x7Dc3udBRBnXShG/Gn3R+A1vmvtdHToKy+rVclOYcSMA4cKpQ1dcYr1c3sC8meg0DJJFeoHw2nIHw6pVDverDoIXxfNb8yl420XOzv9B
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

