apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml-system
spec:
  encryptedData:
    .dockerconfigjson: AgCwxktwHZO1jpD+6aqpnN5j32q5SVH0G112lJagRQd4xW3xXnFEr9NnXRnFOTigzDaNbqZJy/iNLKFOsUGQtzj2ZyG67nx+hWb4bowDszveS7EWBBPHGrvn4+hh9s99mWhJ+rXc3OFxYnUzkyzeHxbV2TUE4U0zd94++J2+3E3EGTBJ4p1LBKatsN2Ov/bs7ArDi2ZqHf9nnJASIAe3awDE2ZEmmanuFLblXe10GEVTJRHLeVyAZ7DWrHFMr4PrxnJdU52dVxuDsjmt/EyvtD4Lh0jcQ8o52+++Za//mYj6N0Mv+jTr2Z1U8TW8BPxHR3aw64d3GevGgJCXYxsCCRhx/4K7gOdcxTOaKNOz0cEnBKKpx3b3++GWCC86pil1BSR9YgSbsuFiLemPjA/bhMRPlhN3Mtb/h3Zr8N1zwrhe5XCJAKL+LXk75JpmnMeSa86v6QJ8RGQRTOmoer9LEhAZEb1jLuuLJxvxLPaGzxOl76YCys6QumkBbgKMJRQXWjyWlSqN2lmalGCxa3hnyjyzK8359+USTtkVD3BjsTKYyJL8GG2sQXAhVw1sD6aFko0+e6jiy5CfTSleN2myYUpBG5oB/+AsnkgofCz4fmehKKbzQGNhXdTGccdRvwPV1mgrRbwzxbuHYVa3Zsvs7JvLxsxX2S6zPMFlU+88iMcv2GP4X3h6a7pZ9IgmWadN2aMa72G2rrajhfDxhMJmRM50GMekqNf7wWhNQGOXnTGkpbVB1sPqfo4pjxXCtZhtQmiDRB42la6R8r1QVVGl3llXe4Fy9YMS9yAcQtSLxoBG1RyNalzqNqb1FWVMsPITvgziP7lvusVyb0kEjvng8/TLxfwGQRro5O5jK8aHGjKqUaOT72TMyZLFw7AhUCxljtrojTrEIYK0LzihAWoHZKjKRXOQJRt0
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml-system
    type: kubernetes.io/dockerconfigjson

