apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgBX8Flp56yy/+QMR9H1Etva1ulZHXs62+rGI7J1B87MalVRXJ8ZN7eTZta+ZN8atjr5mkJKOYvw809SAc84zQgWQe8cPaFmEpW1H0ERl1ed3Uiq4Gk47gWmmx6bq3Lij9nrq/UYofSKhIDHv2qCedVeWYolN/T1Si5tZlPkeINxNj+/Ns2HjFMdoTXPJYvRjtnP1HVvJRY5zULGCH4ugW/IQzS54Ghkyi7aIfIRYauanPRaHzEWp31o1csh8EpEHQd5bcnhYAs+wdvLG4mBMgqN14CnD7Kx6HfhlVMHCxrDahb5QVq6s1oEpQWrKJbH+NZYPxXG8J1NWIcEgckCENQl8jFvKWsRB3qJkSu/jwpQqD66uhDzot8Cn3K4rrKaSjiETUs+tatkSr2hOFWipVTTmKh59/84LKtXfDb1jbynKq2Sp2l/vL+OQWU9VcQxibKBqizq4LR7/j9tC+qh4xZ/BJbOCF5JviZuF/5JQmv6ZDalPgfSTlcuXP08y+sfG+ah6sDFEWPLyPm5tJzpjIMOlQ3gcDNZBEGUsO25NXkXV4dU/Io78AQsPIQEjarJ1gGVbUZQoPC0EID1feqpOzh50M948r5oEcraJilWnYdB/jveexSQHIcdftb81yBbfvs/ueaBS0RrEgfQcnw2hSuQ6uSCTE5YWhVk4jLEP1N+OtzOD/IJFTIjfsbMwnycLLGi+ZTdjPUBxI93q/jugpukypK6PJD0/ctST7oi4gYRPyQa9GwAbiaipnzVP7nrvI7wbU832kOGlaXTcf2nHdXhL7Vltb+bUYYjuz6kLcV78pZiQYhrpkdUtbWV/Zjx1sZus/OZnxTuZwuqeTwcAhSxrONGReJuHQieGkWFGue99l6SdABeoEWJdkaECdLiWo6BauNFjB7ROlt/WaCn64AuxZTUyhB+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

