apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgA5J8OG5uzw9649n1DFw1waRUfVxWnDIdXkCj7hJtpNYDn0J9ut4OrDcxpfcb0VH3LOZ+ZoUsKJooK2Pz/4No2AJ+Ecxz9+m4AbfI2Px8oIaBzuWDQ3sPEjuRq00yGKK4mh1+6C7bO+tUu2zXriHy6DooKLWJFAo0tVc9Vm9OfcKKVwuvKG1tDJWlIpqa5sUwFcvgdZegQVTtf3AsL4fK8hC03ttlIGH9vFGRQepdXb/w1c+GxGIkyOcn0CcmumMKTVfLSxZEJrk3vPZJ5My3BW70nO7o74pw9SswfihbmQm1mrqA336Kp9++bWsTqlc6+kt+A0kWxNvhyh0lqwKwGBrkE590ZiXShGRF2cfUTN6ne4bW8Oj+4IY05CyT0cNDxNFnLROundPM5snP74jb7x6j7mRpMBG/IgA2nhGaQeckXtSf+75aR592H5huOGT6jQOZRgUf0CZsTji2H5+EDmzV4e7qFFzG7qp81BQBO5yRM/cskIlnfkyeIovCTombiV4Zr76yimYmxiVRB2AYXSoLmz2SKOtuoyXZ0+H32Kn3+TUatACihp/8nZtbR/onCNyXLtrEMAtZ5yEjGWvPL22+WYKvZAqd4Im3XjLdj9QV//L8K+cqU6pkL2mDmT66E5X7/01T6EQAjl8KaHyAz5+cIylFqS1odIcedo6mTPU7r5D0m8+qff+kxFt7SbgH1qy2C6ceV4YC8+hMtCDpW8/y2VLrzviU3xTOUzN8ZKCIGtveECtehxzry1NobzG4Vm8PHzk9RUPxh9bSVDzZNct6seBAPu/yH8kL0ts2FoEpsKVwS9Zs/umThDB6KYu1srMuX6Has1nqA+V76HxSXgTrOmBNkftyCjqb3KEkQ73bFeK7CxUDbDdlYdT1B1p8nvy76vvXym4iukIW6T11uXDlOm4exW
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

