apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgCSds0lodZnLUiExMF9l+31guLDGZis2Wv1iuHe4GKorEUEAr3SS3TGYaFv3fc/UNKBgZzI8FNb3+2rhGZlKMWN8f6N3y+1Q2JMSJ7S1qTC39LdUezNaIfDJ8Y6OsVwLftfQ/GRzkitvkjAeOB51aZG3Q2NMspAYNjCTf4Vnv9OH+ux8pyIbA+dhEDDplW9s9/KGEGPyMcDDvkzDENeo3TCcWebI+M7I4HyMPVZMojRH73PfhSYOF2VvjnAOneIdkSyvLNOlS2ZsuPO2s/Cl6ELIDrdb6d+sqU4VLvRHCFAH9xa5b+mo/tYdjLIWSye4fYzAziDiwfqC+LKc7UjLg5dhJRI78v51ob119pZOvT23cDSUPW6vH+Cn4A70xdUb2nBQjxFyH2uHRgxMGnRBSxguQs3Elp6+3Sal7mq/fflTsQrskhUxww6wdxDOUOaJhGV4dojyj367PdaTa/rGxO04ZOjJ3Zzk9I/5NVq9D1QRTxvuqpkqR8SsstGply+7mIHgclUF9HoFi54XnSQ2ZF2P9Q5+lJyCXBCVKojiECmmfYvo14mjatqW7qvCSNPFUVoMJD9eZNJUNmJPk89P1d8CIDS441ew8iHoINeY2/k14Yfdxry3eGoY1Tp8ZK6pyAAY7lzBzIV9fjow2Cx+dwgsvp7dkcfIZE78PFQA3NvcLwmvVtQzEXELfCkfeEZB68i7/RlfEeMAihdU46uc31+XkQfILxY/j754Y4OzX5W5X5LDZI2otZJ4eQF2Mk2iFM59yoMVGseY6/S22zJAeGJ0di1BAv4+KjRpcuvmX/4+v60DlgZliIqD2W9EMC/jQxFvJSZ4tYFFWYzF9WX84H3+z06mZ7Dk7VFBuqNovALWUOhN8sWUPFahRpSqrtAYU1IzF2VgJAkMxrkFaoo/WhXHqQ2srvk
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

