apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgB32yUwSinZhByxQSNmiaU4QyFrsKDzNz50YEoBjw5NqG7VVj6VbnuTvIT+JZWBM9sRrSFiG6Wha/Vv1Et5sbb1+1EqeeOMD/R9/rRKxg+aprgkIXn2xuY0HMyPmxIvsdWCZKF7PIvdKBsxABEHaeiX4D9WMZOpiduNbAleM9OMJZFHG9RyQChxzDRXV1ZncShf6T5l40DbIW2giShs8FzizZHGG+KXrupMXk4QouAxz68wGs28vbCW13oel8xu20eDijmU3QSCdSE6X7TRskq9kzeXMUqC4tKhFy8xEjyLp8zfyv8D/n4Ge8zqNJ9r7BB4ni9XrfvNZDUzyeufWR8P+ynwBp2IIVQbluM37jPVaTolR8oKJDxPZAYfspGzorxSRanQSa7Aj0PjO77oRTIsx0vFw0bEDAFZJipZSELyatNmbwU+YaCjCWs88wKUdP23YJuunv3FwIg/lTqyk/auepZRWZvxhAzml55qsAa1Tu122lyj40spqhB0P7VcgEdfNQfDdMqizlj/Ht2/aS0TVDpE0GbYBmGuYnofRxHB5EzoDNz5C0h2IDvcRgLcNRlp1n2LWUSxR5zO+bVU4L2o4p/z2kQOwvrVD/BF6KU6HkO4XjR70k2C80fgdQIxpIMHmEOxZQZfOCKmwz9m+CgDj7xxE+7dlRTEK2lAYsuq0it5RYA3OVmI3o7Eivsm4Ey1cLVVl0UnYWt+JsLCtB6dGkJlO4n/5L9Pw31QdGF7vZWB/DH8R8aRwaGXOT+kJgOqftfqR6yNQkrDhYjAU77WgxSTRSNOXjv65FvPZeJjtOMzPuMEYwDjwL4wmuAmlPeKszyg0IBVMQg5QKuZ3cS24mBG4DMte8Fi5+ClSoBc4+2LPiIA4A9psGcYCa/uqYL/euELTXLGX/F+QreTTxSC379NAo+a
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

