apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgAyskfaCcnDRR4km92r5bJWwoINmSHaR0bpKteF0msAlhnRS0w/vNpTQSeNgSFZZ81RDvo+07uiWCIs6b2i3ZIGf3OqdYe3Kzp2EU3MkUERQy3+hLM9ux4OzgXsJxu8GfGgaopa8Xwi/ElUiZVueOHlwdp5ZpQOsMHumHZ/QNTneBTJ3DHfIYJEC+PVjv2n0fkGVsM193SMxeXVpcDePEHouGMJwPBOnrBSrf11V+WorFd8hygLLRf+G8w8HTOXnSjPRZXFOk8Ie7QxgpyLZR19C1LyiUibfq4FrIgUVgBmCX2J2ZjGvU2yQ9+VCoAnSco7KJl/4u/VLwDbb8AxFfrwnbTVF2J5XcVO9ekVjppZ7uEekdSLpZgUlt7eyB3jS99qDdlTGdrrHyIYLT20pk0JUeMX5FtowyWIl/SqJUI+lRKSMSG7+zuS7jRqv615LDTWsDbw+7ngKztrc25RMmLixPA+Etjm7BbRveZIvJguGyfolbjynfWiQYkK9dsGBAnfNAmeQs6ZjDanclxc3gWhizWy3GYnX8mYUWiNjP5A9/+Ep0PyTcVvK4DiXizEpvlCXmzaH9Ous2aQOYedIA/NFqaaDL/rBr4b9wSGTgosWy3s7dYbz+AbyWDH1JajwWXCkuXZWuQ3Y9pMtgwEhFFWI8vRYpBaR1CsCnoyQATQ06BwBe3wpyKIsFA0gM9E9h58tIjtmXaampahBl65spWsKhaG/GNh308xUJmt3caebZ29J1dF4HUN/7WNrkJ7eL0/U/9IelffXypld4QszkbJiAhB7nU2jh9VE4eResVQNPSDrdNRwSBwfignR4jZ0DCX5rT6Yl+vxu/wtC26s5g+nlRpm3AucSfAUe7WtnGmdKybqJ+0eQo3OAcPROOO0AIlIZRMAlJ9L5uBFOBytc+q4+PxyhMU
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

