apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgAxExAQi1a9FV1kyDJZTHjxE1qfyUhqlbm+JTzurWqYMh7LEgWS+cygN5XnuYCpXziBie6LrTVYvlNvm/qGYukGZJFIi6W5zASHQUsrPSgar/FfZArzPu+GK73ZbI0aMhskxPwaF8EALmJcwZATmwSxZF+TgtyiFVvf4SHxTDiahATBHEmsgaOH743/d4LfDSMRDWBgTSJYjSMoy2tEltAeAk8HhG9GB2auGIDzSQ/tYSCuPpL3lVReEOl3H8RZj+HNPWMpPNBKGS+kPAT9lu927auuS1FScksjxWreW7LpmNpe+mbBmueEgIUMbQ8/JPEMQABSNs6IVpw2bxb/+oBSseqJwzxgqIdpgKWH2sr0dmwvzona/AHoMZNXjwP0qnvtuF9LXS3/LSO1i+WTR59aotW+AV/9TzowxPaHA35iE0lV+9T3lQ5CX52NHCwyV0wXQrIGe7yCihhYSrQz2nbf0Wxqvng/TBRWA1HiF6XBRhU3rLlhNVpaxS+HY/ETE3wrxK+V8ISqnvUjvISicwg7Bwu05UC0bXRZE5ExAjY6R6BkesdXWZfEixEEtZ3M472T2en5H2Gto8IhUx55bDr9cnaBQQ6uZnfnr1Kuco4BH21RouPfmjAgLBzWpDjg3lrEyCr3PHjlOX2zVCpPISfa+YT6noWL0qyyAWpDXV9rv/FzjeKGm0SHIEUHl2bTiFhG55kJyj0E8j7IYf39k5jRYim6I5qCFpGQ6dT6A6gbrEWv/GMQt8cuSGWh52uIFuhsbwHIUMVMhIJJEDvjaNVvdu2b5+cToo3ENg8gY9wCBPKmoksut9fUN5h38NZhkge8IXkpqPQckj+4f7I/3zOFE7p4AAKThyMtQTLhDycf7VyDH35tRQS75pj7Ns/7IDz6jGVmXzM6i41dfudMAIbEn7z6L9bu
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

