apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml-system
spec:
  encryptedData:
    .dockerconfigjson: AgCZ6zJbD+qh7XOey5uwUBUxGRhiuWLCS3YctUWquFgwKsrGnYkmqiN2XYsMgWtx9nxR3DRT+Q/kJyh8conDN7PvnxlGtYJPnixTwG6S3Tfq+GUPTSVs0LT+tjZ20mlBscap2Zt/3qxapdmxO6UtCWWtwim0B/u1eDwT4Nv3ZpLobuxOIOb6D4onrQTm1xZtWgkowfZDUfDeh+CQdJdWjAhHjdD5lF3yziOqZoRWJNazSeDBWIZ8GJbI3E+zSMf6KqIoHaxQC0GagGc1xEtbZV1L9mRhoIcu9vtvL12JtxEQNritj6GtckxNYMne3050R17fgMDI5zFJDomBTzNEcJzOtcBIjDeC7++Ks0xgmj5a6skgC4BQkagWXh1mDuWlb8szVTSEDMsrvqbpCsvxXAZsJqCRwtMaSU07jnos//9Zc+Z2/1lfNexQUvDO4KVFd25zGWkhOrAIhvVA+3BxD8GGcCuKGZ1UGJhWxFgcEzsX0Dg7xtcjdnuonyOuXHYpkLmRjCwRAOyeqOEFi4ho5pfAZAwd4zRDLaicaX6Mx8mqem73X0hKl2VWFJvGpORJYwiU310mPG+dnN6QoM0yJJ/VE/o9LOxBzBMOijzCrnneyCuZDMRZSSiqAyuCGT+RaGk/Kt/VpKtdyHbHDVZEDVhHETny942u9XpU/v0Y0YO8OB19tYDyyvw2KwiYdAV09ww2/FcZeCIXg5pP9Uf0wF+8nQSZNVwa2W9swA9xElsxQ6xAruePB9AHIVb9f10s49/C1odzAfW2ueQgqCDFOvNlnyjczRctFrmnDtXaoOEwHBvhY50tw8Zpfty2kupDRq8AeuXauj3qYVrAjzVpLpEAWwiJ8ijg3DTUxG83czX6UeXMIwZVs4SXLgZ8S5eiBGs4wrtAtvQnegQ4TeKvlLjW4sEbB5+Z
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml-system
    type: kubernetes.io/dockerconfigjson

