apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml-system
spec:
  encryptedData:
    .dockerconfigjson: AgCD1maOrCjxNbAVAtK3vx0x1chG7p5adX4B4cfytMeAcEe6+gANFK4/4pnboxYkb/T1Gon3htbg/ms+SN6XyTktxsYuX36tlcCzMljoPAqXUaGhouKgQxmbuBNqOOoXZDOTnhrSSmQw3DzWf+oON+ZG/l8P1/SVwSKqKNMKTjW6TAvUaL+VKwqqCrcg9a/KzoDSRKaEkwTO/AxlPhZIYvlznOVDPlav6YPgY6QrXV4+gi76oliDXIGyzakCco0M4HTvhVy3lHReN1ctcGJvXxFLgD00CDzf6FhDMd6Tkldr+7HkHw1KIxqoi6NJxQ2eIucbayQwkXb3rFS/4FbWK4Y535RV7yAmS0FTtIVyJFEjkFqsMFiOASlMZzG/KXMXYEBWsBY1rVM3YnUm8o1GJYOMiE7EsyR4nMUI6nf86xJ/vJTh7sRENtRuLFX35I+j7icDhTkYqIvNNoBIFTbtrHV0HCWMsY5ppefO3l42xp4/rLsAI8aFoCzOZ8oNMSJNmCAG9XonheSshEUvKUIeD3ms7WS/tDlsz00J32YMtAvXBhlRE3W1PY2WZWwbhkqxe32svqKVfyEOU5BzGFPQh+vv1SYWBYqnAl7albA8qyTbig5GS/IgRY1x8rjmTYEgOSXlwujwQ5wQp39gVg7LrkZGlNEoBfDn07fRKXbveaqtibRuzH9RYNDxMJkoA2tM2BpBSm6W8ZHCRtTyXrKvpS3LRINp3VuzXcRs0IzPURWBPox4QsRKy82FkLLh9myWvonRRIFoRaen5mT5k8+ozt4xuUm/ZkkvxeWS2U5gZJw8g3vGXd9be7zs6LOaJyWlCzFuRNHigMKmgNUAFF/viTFiCjgEeVeVwE8EAKEQ5n6TC1ZLb/R+lnblIIUh8dbeoMb7QzKdwTXAH20j7SM9pPRzIaexMoiy
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml-system
    type: kubernetes.io/dockerconfigjson

