apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgBptxdCxJZQIa5wHyATitu8Z8tiKkHVL1jFwbJDrzwxlK8zYDifb7WLp1NnoxudKBey1FHpTDBnNsZtizP5wKF+g8aMYNLNZIOc0DEIa/QPt/Aro3C3cfraSs1BfdA3XoGMl23h96/fgddZQC3jnDSsSfkg5UcGU311ZS3X9Kbu7H8TXWG/AO9rptDfJ6SZg67mnXEs7F08ZI7GRoEIivV6nghYxpXDATor2JCZwEV1DRlJcd5qFVQJHUIaWDyG+BmqJS/GrvY3STWtetW3eGmPuS++0Uh1eN0l7AweIpeqqeNG4umBbBs+j8rp+YZXYxI1NyDmWZcM7nLoz1sewK2IjrHY7ZB1RGOykBMvrcX0iQwo3XGKML+J5YJma6kYW9gCCRQz2suWSXUP/qNJLWYn2fI/x7tKD1QpHfL8CmzCoTJnW4D1jQN9XeyDoR+0BtQSGdAucSiYrmfXg0BhPTtgkSQsUpr8esltwu8HNhupTOd5nKMx13a7cdXE6GtSHazru8yrKKy3hPGi1YeKknNxaUFbKcPbWEjXM0PleMLx8cwGmV4mQPlJr7nMCVwLwsOrLg/Eyi8K6WK1HPTrZWsC6sKS8A1d0hXKPA2tm1rOER68/riZcK7fhbxQcCqTJsriODLhXamgZfTujEJdsJM+O3VQF8XOjAgV+H6cFCLD4QzvmF8mLruNevCApShvyzptMg3M5epnY7hCMjH+r/fC5t0RaTueD4fG88BR6sJt7BnrXD5QxqXxHKk8y25n52FcdMjkzgUPbkQil2laQL1Fk/Y7RmQb+l1aO3VOYWXiP2SIGnjY3nBPLvOgOz6Da5C3WYyRpMCasBY5nbnp+D+UIU2Wi36dja0Iyzi4MAv2VnHDvDMjK9GcB6SqmK/uXV0FxE03gJDgfpd5vwuzppRQI5jOLGqO
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

