apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgDH3T6l8tDxwcIM7fxF1M0pHdZDVJCNinlLttCedseDX7zzSjZoFh0XaN1QjHEKWtCYDZUFsrBeCfNzPZQNui/3zC/NIFY2LlQ7IoKhx53ZgaJkkDtXgeJKbV/dymkLlcg54dmSQKsz3tw3i2CN+gkZiASZLPtsvquKD2ZkQMVLDngRRP9seL1iqSwuidHjVD/HuaSC67fB6e4yVRtkV/k9wuyxIts/87Gr5XWZoKbJSpmuA1xK/fwRXdZdRqGbTWXPpeveckROrjH8PU7toENqAPaPj+HnBupBu8aVX71ykZM+xNGMoMfQw+C8s8xRiYdTPXH776nXtMCmL2526BgcLkQtvS+lO/00jD6/rePNnq06HUlHoShNfHAoWrQGv9O6fTT8EfWGlgQQ+E6DvhWY2ekLtIjnlqVSYY6GEkMJG0TRsMBWjU06UjuVAUutjo2ReLxzNLuoJtyQhRbIEUY3XrlTcJNg8h/hy6xTbv0h5wLbexY+R6bWwHh204cVQRcSM973RFbQLQL0A2d0OJ7uqW2TjY2YyPEXXKz2l/hvuL4rpindvdOf5ICdFSg5e+b/gGuFsPvZYsLlC893rlQjcyd4cY6vUkD8YFhwJ27E5pDjivTGP+MVWXoBbCcvIH8J1cuA0vw1SnGtrGUFZnpWce2EoUcT7GeSRRnnMcZkd9UpfLa0WeamjIAeG0U+N0jdjRGhRrM54w0tuRXWVH245tfMglxDIO4AdcwSdRPPvDqiudTiMDOQDjHgrrGDqD8G9GuF+RI1IqGiwxmsHKbZ8mQJCD0zDQKUH5TyuVicYYv+LrGrvlqqfPrsaaL1viZ1yVtecYs3GQ3iePNqIJtvwcYDXWCsDfFf36M28JhWObKxTzSkoHb08Ff6SC98yrv8s3ZFU+bglU40cfvk4+OhiJUbd1Jc
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

