apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgA7b80bWM56ztvO2W1O5iXhnCYd0/GejhBujQ61Icq/wHbi4g+aSws8tK/Q8eMWLtBx8ov2IBFv4kq6tPtZXubG1QxnE7HB229uXQwbHWZj4h0ctvqvakVZNvbSS1p2esffZa7Nj7ypDgCGQ20uYjWDw456w7av29k5JWNKx657KQCNOPQuEPnwE33imvqWZGRkeSwdK3pytq9Fo5aTmShDUFYHFOC/Rt3qz0QcAdwhLEe4NHgV3b4sym1hujqwotvmZbIBmViLAjSQuFK9Vma044HpbY9nXCdpi8UvxFRX7tgUh5d5F0jSdQgseRUMzSFDk6Ybvp1RMJteBxHUcxGeXiaUf4OtovnTmA0j8/DA5YxxQ0AhDcy9/T0eXyiSdAvIZw+Ni71pWzSne7IXcXrr3sPDZrAsOdfiHnWbgKunp/G6EFodQ4sMxgDijfwXA4WHNMevQzRwBnrlGoXJP88OCIyocqENTW4wfDo/E/qwXq/SRlpdsA11uHJulOA7k71Qu9e8cMBm7ueNuW+x/u19OhTrvWZYK3e5EvgzzsUG7ST1nKTi9r6JLTpPnbB08dV+zaYlRYyqcFqJEzXndbR7+aUCdwOIsNm7ZHMp8zEHjpXxzxbBoJyO6ot5n1aIsaIbxLm4y6Jo693AO5fDGwTRMEgH0cMml0CNyHkXe6/IZPF8CQYVen/jjeazj0MXyDrCLJcZvrjw8V7vv3Dpvi6g4eNxymDqcrM9JWaGJt4m9U7fj4AhtSVa+ezKPl5f74fWl7SrWIOUePwvIp9lsz+C+mR4ZYKHBUgm5N5yDGJRvHDtuW3VdoYeZXyamLaGuGTdKT560eiwef+6jDYaRDVvmayVVKVVHlt3p+Wd6SZ+dz+DpHorj6mKbdAoc3EaPU0gGmTk+eoG8/d09n+3nNZdbUQN4CXn
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

