apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgDPat/RS83MOIV6hwFVgB+t+2WvewCwTORtOPXrmsWOd5bGT5h9VC7HgrvkNLwr5qrjmcPSogsy/nRKMTgpMvoQMfWEzyD4TJrDIhksi1oyx2Ky4LjbmPDdy+/awnkFujRzQ8QRSNi+rE1/NYKjEZZk9s898IFMDLRKsPTZCH2BOtCsk3h/fYeY2TDszdqP1arkvntRla/Wcbcbxkct2+9NyweFmRAid5Z8p5GBYY5QcKLUA9algDvinVmOzOCxaJrEC7zj7dxjbn4EJMtP5RU9UXtyLg4mjZqXzx4O1vVdjmoJx/VRQld2/puGO8lqhPJ6EnI+mEHK1lhzbnQSfn6uVCN29WtWad6/pJGrhnMwavqqlYnUhi112JEIieKZxKsqhdbRgcSexC4zFuU69yZN24CUEyjz5vual9EBpJ0mdFCX1WwX3+XSFTvrRuBv5i8DUByR4r+GoKTivSFuq4zz3+G7En/vT9WQ0g3mLziWLv4DkoP1iUi0J3lQm/PlZuzHHogsOcZGNCtoDeb4qxv10E6xBSzq39YD8isyj73Ud97e5S3MNqTD3x74JNG7Niu2t62EX81oN1JoOH+Xr8qdFjQUqZmr5k2fJ/CAe6EhMhyN5h48k2VjeJZq66tZ2gxKFToWpVHfKBu92mePKwXtjbAUotB0dPTpEVEY20xkxXhmJ3wFkBUcS+/B3AWZDsqlKSCiv+5U2nsnWxcSCkpgQDDaCUPqs8/Vlwc1DSCFsJb/tdFU8mJ811IOLEC6CECDlB2SmQbviiQkFeljKocQ7dDk8kc2iFVLjHHBzQ2lseOQmMCYYGuNZnm82Hgebhn6PsW3a5eRAB3vtfJDNGpX4b944tf3YMlT7oWxOWTNoDf7o02lAguVk8Lsfs4mLgVfbuy3r+N3LH6VFrOZCMe6FQjKAW6V
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

