apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgCh28oM5qobBeVX4q7Y4kSqHk0RFv8wDs0GcSrrgwql8JnhKIKIivrLHkXMIq9OQtA8yQH1+tFKc/4sB1OghcIeIDm4YAsPA62gZJw7I+SIIIpZS1oTBcP8KBwgAsbY8tGQf+Cdf4Iwv/EFYLVfXcOhpgjYIlPpviCZvqokAmBxVw+245j7xDWCz324Upuivfo7sr5eLtoTDVKy2V/DPYLJZtoDpNio72MDUbOvleUGfKq8LeinmyHgQA8JrUyqWF8p2pvVrCLgkyKEbNReYfx4W0kxlY+OS9kXCO8OjygDtxTllY1Xq41V+RS0b7g7uXMIheyQ9UqGsvibrIiRD29qgZZTkIYl0B2RWKwNXbB04GU2f3aG7U4RveD1X7da/2gP6EIB7iR/Mj2PrkwbaL6L6reB72OsDbIOSRzXSlDXr688gUzithzPCm7mXfoQ2g6ev5eSHFjVpP4tlBX2En8jYxT+RtwFYzO9AIjuZIFpCbot5pb+J4Mafox9qnTLLvfDxVE2uYeB40Wm85N3RY1CL0Vr0NF55FM5/WuT1I62as1/NPgnrhyC05aSDdFxQHxSqMl6Wf0vHIebKGhRq6nPFnq3LojKs84snXy+pYr1GrAEJSgH2m30J7GxaIc1iDtZrX7zX4j6GpIP/7NbnMYfUkR8Hespv/Tb/xmuEnkGhJh9GV3EvsEIIPASPhL1xI3TkzBersdXLVwNwuyIQPRn6/H5kT+PE2jnV4JiSTBYXJWRUJbO8W2HcaaDK102jrlSFVBVbI2f/gAxhd2ozLHBbTk2UMkaYChKqM9aZrJbBWJkP6JFG14CA/eD2QZnrVVzQd/GWQ7uX5ndEXh0kXwLdke/lTAmyqASL0NPqtDPj1SzfiOpWgw297vs6CzQBOdGS7uob4C6EloRMu1mHgD76RHiSEbs
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

