apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgB09FylO8YD8uYSoGSQMQlC0xQUegJ/ce9Ego6GDfmV6YW20+JlNTfiCHKgLbkjXSE0pAAvmV1bdN4TiELx/mtZn5y35WiMWVOG2DIx0my39u0AMD1M1r6fzMN+lMeoLrx4U7pTnScV8pw2I1Diga6xmJYbs7Tn8ed93PcsyG696aP3W1xUGTJrmCWqdBy3LvZXkrcKhhjTgSjsv68AJGH8Pisn16wrpSnHt8cw1myGvkRiNboX90wmcTDajzR1Wre1uwsTh8YT9IUNP3VWAjHYdBpG7OuUB81hDa59zW2pWZSSa5FkK5EbreurYfvJCLEzGhtRM4aRzKXIEwR4TFK9vRpkGgcttcUJJRQRrqyMI/W6CtQki4J+KsopLAY9heDkK/ZP30wb89pCFXdaOYzGugc2RhsXfzVESo0EjmHVsFT0FfMBXfpmWUGCjpprLhMUQMEzZgzETmUlFpLdq9qDO1/I1c75iZdgWQyx1FxHfCz12zIH7zbNd0vxDkUwaaKS9B+hIpavqUq9elSeEB/lNpQ5ppyfY/4ARjQNT5DCbKynOtnJJhq5/ERnMHhrOcRzCqdsRJ8Cwhsgh+pycjbZF8KorQdLpOslERPRuLXZxzg8F7jj0MJBa+Cdc85/Ut/uJY4Vk9e2F6XE5N9MNW12Zqcnt9kfV4AcTcG7FG2tatyVb0AZvwRNpKc3ZelgVVL3gY2syNbAoXsCBim30kPyorxYsIYVoeCD+yCERTHpmVy4Mv3x+7qQdeYSF+PcsKmaMwdLItyP+mCCKRaNcVLQ+mwnnhpY85qVcPy6blPSQijbd2zI5IE8iOnV1Hw1F0dCRSHpG3Fd78AuoHDIdJXqj9g+StGM2fhknk8Y8aP8Eu6qms9K2M/oVT3Lers0Jm99Q4UfjTz2G4vBs4d27e8P8WExVWzv4cmXH6Re9VLIgQ2jVeLPknn2jItwJD0VS+8z6bwlvw12k/mABK+t4ToW6uJKCghtcMtFXPj2oirFfykZeRQ=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

