apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgCgNneqP/ndl7HdyhWn5KEQVtb5xgmYjHD79boGqmlie99GStairzz0EaSxXfBJQnLNM4e73sL+nwlKLDbdtPBAEHdSjTEL5saJStqR0bb/uvxt6OqeQjJ42qdzmmVn3cNyYYMlHXCEeVu6nuADbfleZXPNGGYJuvT7i3rLSm8bVfg7CzTguEfEZdWSvSMetSt6GDs4mAac6ffaEOVSqdCAWbriECTD8I4hVRl/l2RJ+WDSPqvM73UJg3VqNSjeLhYH3vRT2a8I5edlWrsrp63HG8p+ac8h8qj+HW7VH8op1N2iEfeFWg/J/c/bhpQZP6b1oXIRpHmvLjrEii04P4n3kTJmJBMLwuDjUGz80+CEGyPEhBgtLBtcDaOXz5DogDPSpeOYQnRwrBi7NY/JEjIn38HevFNka0uL842YiEqXclKr58TAIX+swuK1u7kx21k/IAi+c60bEsZsvuTf+D9GJGU2g/Zfslr5aElE1P7zIPU+/6FrxtzefVDERH13EmjpCmS/VipP5pJ0Bg6r/8qLXgtfd21bnCTvOB746wreHPqXR0eZ9GqyT3btZ70YHeXTUkk1GBLkxuHBZ0PZvGNMK9k783z8VaAE3cDYXH1VkkMGfUGy+exCZRZBfwp+zyStJuLrHHmMnVT2l4Z7aNIyHT4FI/4jngUC6ESEfvPOPkopKNYsY9LLs7mxQ87kEbE+eU897EYX6V98fBLQp/1vPA7MHRPhyztjiNkWXVIeh4K8QQfKm836c9rj5jLs/GtxYuqIHSqAi1+eG042bNs+s+/tJWh0exAC9Zmo0LG6JoFFNbUQsIN/EZSDiNiPv2mHNui6p0qPTvv3mcLGicnTEXRO7F/rzNqpH1i4CWqnWgmRAoMuYPwPQ+ixnaIGTwKg84AjDl6hRfEvTNJ22fv8imZlxZue
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

