apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgBGzLdit37uOktVpJ/M/LbRI+42Dl/LcHQ7e+V6mJ6p1tiCe4D3oyRURWKakvgIk+3OlxhZCk+K54oN2FJMgSprODn2MSbaNsZDmzOWOO9XpkgHsIf7KtJ9lkH+lxEyu0uFaMxi8D2P/wPVNcsIrsC0Ci/CNEVvQOLOQNmsRUHKUYg+Q0Fg/e6c5vtybmqZlmUkchm43iHiZmFiOXVwNot9OsSXaF4vzzknFYtSfVrLKQgK6DJqtPNEjrivUEhKcknPUr1+/PB8arVyZfhst/Q13DKUypKOb9ye7nFIdtSzUXo9H3JjWNDChuD4zLMNYg74DOHLDmY3377Z9traPv5frPdw5vVOfFQ/CoZ+sgjMowORN2Gsi9/cHdCmep6sXjQ6dmxtsEsPLmoSjuTG8oaKDkjXuMKRtZTimbP9jZnRqXhsLPafgSOHsn/fGj42iKvBM4SQJjPabcT4VM0dqI9EQ/q9k6XiwY4hPCi9qE9JbMsia52TRwi16WYlB7HYGbF4BbfctQl032z5DuS4xgveLWNRBO8cYRsEr5LDK/SeCVKbXESX9/S3SIXjrKUoIkcNW2S5lilnLYIGcJTsViIy7O2y3My7cy0dACHBvRIWI5IUa9e4cdqsK1M02jFE/fN9BtCzEuvjLPhRqukdHjpcE7efBu/3hbvlAb2eIgpZ7Tzrw7Xykk3xmDa7Wp7As96xuEJig0cqm4l1G3KUR2J/VqX/aOGJdftFsO+lp3x+defKwi17sBI1FCdVfuc4rou3jGnnzl6jLSYilg8QI0skiH0zy2BlqL0iu7rDrMrHirv393EmTlHGeHtE3Jv2iVFHV3ufjwRLHPbkP1nwzIDljFL2v/7Vg2qV/vkNLUH4KeuWwHIbQOUIk4exYLG0WU4vsNxdYGSsmAzhw+hcO0+oAZLRwMQZ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

