apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml-system
spec:
  encryptedData:
    .dockerconfigjson: AgCRvBKBZEUIypeFOu4LkyTCf7Dca+vonMP3hcEe8YxApFwJSNqWiTGoDRVecfEKpgCjVo8lVjDKe3H8qcMqbN73o4ToQ3atLpg+SeuztyTqDPtTC55grPbDyDnk0DJFdLzR4dqEOYM7rWI37+VLvMWBqpvV7JebSY7JBt2F0MqO32cgRynzA+HKP/EgpoFfg6eqpgwOWwnn3g4Qk1RgjaIfy1vkqFNwGZPF/YPcOP4w28U8F6687u03Dzm0kUCzESruTNtGA1DDWKdybSwJphlE+qKtYf/TXBq5EfszWuAKyCewsmKJAlbb80DC2PqeaQnxLXvZsSmxaRgvdZ6Rpmt+HYGw4wYe8S87zkSrJwHutKh1pjVSfnIxaqtrb+H52Rt/2SencuDjRG+nSxnapmWQ6q9qc1V2lhboNYPJVEe59ezwMSwwcdUskNmQ0EW53z+Cf+FWJZc+Sev2+iq1En4CF/DgSEfVs24fRnL6MAO7K4zI733lYsxR1zMwRoYSsgUHx8Ovbgy4ZGvbYGcZFQKZZfTjcoQgb1zf+C8Q/5HmtB2Xux0oS3Av1OCmkdv6qO1SXByMEhzw5xqd6Brtq9UyDeZyYx82NhRETCNkjyD7ByaZGJUCuLbH0alMcEaFn1e3noZkQ6ePXyhj5WFOIBmCUaG1We/9znQjy9DbBKMh9SuiGWbqLz2smpqOzhibciT6pn/YiaGSutk8s+7ktOl2YJQ8zYWBzvGcaGYMuVGxa3oGi6Z0btbGmCaRalk5tJQfMN66RrGm/HkgB69Vh3KVoAr7ISIISWPEYihwsL+jhGqHLjYvIF1khMn1UvrbERfBHCBFK/wOLN7n7fxYD0x5vclMK+M8qouvsy6dih6KbhH+gEV15GI6/N04eBGHRJAdvkK6V2jGRX8GOgQHaNxfS+ObN/o2
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml-system
    type: kubernetes.io/dockerconfigjson

