apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgBkznIitYIBq1OE1kwRpGSC744lLzm2gpxee8yCOyGAo54vvc097+/2L1NhiGLs7geEP9LCEdSHpAoYYkfsWG1yocrKc3hmotHBXuvr8bci0ZO8eBBygKuZ6z3CYp60v4+Sc4fm52vNv2Uc1j9q46OdNTvKH0ipV2iWWd+vZvOKun06jYHIlxWIwTtpej7qQhDoK/3rIf6ys7XkzcqxeOIi7z/1BBOY7SqtXn3OfOI4tlPzpEiSB5VSwqsKogcNsuGty4gXVtb0E21Oy1yB8LSaTDZAmQVMTCqWTSrJ+4D+1nbU6Lm9UtZn15Fj2w/YoDl6iOZ6j0bBeXmBG1rO9LIf4p9igbV48ti8Gv8Qie+zmAkBiHevKpziWLcLQc3yfcVmluYYSmwbaCugByuPTnwCaoi7x7/4y7js5FIxlLp+/fJPyhkG3xmXRHGzl1V37bJ0GIIk6ZWZa8yNx7PMIqgp4C9PqttVHoHSLpuZ1z8WBmEvLXRO0mz7mo4WhHZyV9H7VHUry7tJAO+ab2YvXUT8EOlIj8rLxjQBWbxEUZxy0vTcV2Iy5pEgFNXk5OYZR7H+9T8GB3qx+FzOWzBQ6LWKl1BliTnEZB0Wg3MqOtRynM+l1/QuCbRkX5kdnqdLAMlEoGFpyhyz0h0+6STepJVe+5dvKgDmfgfxUiX6vNjL1oCvxHRZ920WvZBXGE9aqrgRHAB8vmxw4fulVx7N1PVf5XVt/tJ2e7cEMyEZtMBRnvlOqDjMwIxweOYnFTGMHRubrBJaONmraxO5tYdmo9s9nExyCL10IYoOmkaQAK3iOHgk6j/mt0xDSDDXn1w66QPEm6S2tX5BP1jv+oczh/5YkvMVjL6cUYbAonEjKasJVC0q6W7sXkW/9RdQxJYkOklMVfNNT3oLBjWOI1mNfrBoAj3Jz9Hc
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

