apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgCG4UyxFjqN3hWclOQsOv0lo2J0NV5MufDi5PQaev9gM1gH/89UJYVzo/myNJZ+ITvswkil3sl3E3SRqpG4OYPYAsTtLBe2mwZYdcAA6q7j7z8am0xFUduNhnTJ1hobffgDm6YuabWsOvnPAaQgt6FyJ26D4HL6spe2aXoPKsCV2aW+cIjqJbwdRklzVP1OtK5lyZ2CnLR1+fns4MC3sBNWxPNpIh60r27/lFYOvBOqO9SvCeCwhuzuns7dKYnw0U6ukskpmEOTEpm2SOte/og0zwdSfEUlZX15Vp/mLVCZqY79w2zZdw24EFOQwRlS/vqKWq+CVKQbRNjrs6ci2l5vP/9DsuK+Gu+64noBS+StNnxAj4DB8gPX8Xt1C6JlT+qpQbcwLndjXJhQzQqrAndUgDMP5pagWP+UnRmwiI5rzZvMkjX+Fchj7wW/OWZH7HU/Ytd/40IYEQeoLDeyvZnbR0ILgMBXSBJzP+06v7Tg0CIhjEkKMy8pbEpqo8kHwLRi3RqvNsXxQuVh5OhiHqgxFWHoWjHIroS8ckJ13dwNjXkQd2JT66gpTfAuOrj+H7KPkgYQ4FNb0HHDAhLMidGTz2ZYZW004SEjCpVDhI0OVOgpIkTkOtccorNx9NeDl0ljuLLP3ayxFe6qIEifcic2kxCGe9ezghFh5sIV6NvrFKX9mtVEPciA/e87iohFYoLi2EkAlUUL+GBNfyFJZds6KJdSDafEejJO1QkftnbdviUmMKHz7gQj5Y6Lf5beETL5Nx+KhFgYMWzpcEmQaf6gLj13GYGlWNEev7BmgDr638ujD/CB1CbJ0yX7dDM3UxHhRZzM9k9+1XSkZVVBFPvvgEw1cSX58rFrhQXitT56HYY3GQr+sTQlI8DQhY7RG06FyMRbhH5v5KfWH3Fc02vTnF1x0sV/
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

