apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgCfEASUDq27MIFyN3qelvHW9aEtLIJB682C99+MN9qJUR+GLZGaZKSsfG0XIOw3MtCVFFAge3CWFvD93ipF/dOjI2LMr+H86oYjCDXHNZvjYYvW9UHBhFSgrindIaleMOKEDBJfuw9FII0OUIajA+GFCOPlTHlS1wCNOVxiHqqBFs66ajvrE8JU/BNFKbLPEbe76hz2bZLupTYmAVxnj396FWj9P2YyJiQ7d0zSS544EAH1oJ/tBUi23hpa73eqNn1q9iNs1U6hkQMIs/f8641nFv7KombWsn9G7cVfPL9ofp32AN3Il9sSU8ThtXOxGKqj9hoNMeHERACod9kD6WZMwAOmLe4N+q66qFwviFc7r9W49uCiDnAK7/nxRi1yP1hcfzCuATNxwkvT0WH2wURM+WMBAMkR3J2Qbrd9LJV4QxpiSaMvdh+bIVFxFhWurdmvdtjZMT/CdKoQOu9OmrQS9koTwbn1XQmOuHr6LTei1rpWdiPaskKGM1UmuzRgiXzCDUpsDL0+vfpPpMejQCHzMexuZitw+TaslKRVIY4jfF5EeJtPomj+iee/AzzQBBl/AkTnlzWlkAJNNnLnnskP0qJtU5MSRSV9NNBo4CAESq8sloYwKSLBuR9mdRASK/bvJG78guCjZTe51oYLTmeKmQl/yl8b1yn9I5sH/18CCMLnRCODX15UjBzkjiLD4k+BJZMggpjI94dFo4lqc2csPQjBGZ99EuwbAEv6Bwzb5FvsIlRxcjngIJjLKbrMdRZToVPgSNJkZaiq882RxZ/AotRWLu7wNNPK0vzesN/Gn5+xHRr0Pp/MonqziGcloQRYiOW/T4rdnU2U+yXKFxsZvIA1VAXMTZ37VHozS42d6aa6+cnI7hC2tl0sDEAiIOfXKiduFidRzxY+Z4kNfvznc7SnQxXF
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

