apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgCwMXj4TE1LiEu4qNHL7JQQ6kq11O0LXmhrQ8awCB75TH5Y+zjJmP9+0ZOnHaLL+GyDiCvc1O2HJtr2RAW+WtnPEpwcfbb6A/Y7RgPOLyKgTtEm8BiBUIQhVf2EszARjg3NbTELbEYbe0RSvaFh/Fe5UORfg8fdVCWdyyHFJidHPskuZ7QRBF9Gp3sAFONjs0C7DrOVbghdSIENsBX6H7nDC8JT52cawWUYU5MpO00XZdLipO56iiMtqtT47O0dd8/yayaQ/U74UARwcaiDGrsMEKPx6j6bq1Lmcp7TabcaclyynHoiXEZ/o28RuXFBMI2RpxiTOr943MC4P9XSF89o42tw0s1TwyTCYsQr3mPDiu228wxL5ly3FgyW1wdJ1SVV0TSgGdrBsgJj2FmcLWOtjplW7Hob3RPCs5CF7+PGY22czfHTUWKi3k41dUQ/bIA9nKYiQfdiwHLLEJQdjoN4ep7ZjqKLJ1vpT0p3r4OyZRGuL4XZ8U09Vlk2U81XnGm9GkDvhOQ1kxdhM71RHPH/rJ4YxHW3E9JwQ2cr5IJMGzGn+s9soJtupdVhv9P2+BIqh9OVz5aryB3FmPU/RAv26ShyxOjyQseAcSMS1KslKfZjtQpTe7ZltFM0/w6uxGEZkrNKqigBQ17Ud0fJMYe0A/lgYiQeNe9nFT5NwnQ9aXFUkpuOjqWvQ7bkbqVe171MyKAXJcAP2xw0nNQ0UKvFnejD8R0ks+Xws4PFKQxsPzjOLYrbOqMDrXCa89cwYf1xEk6EaFWyVrocYQbNhFqU2TJmexkXCC5Sjrd7M5lL9wzOk2nRwv26QtT04qGWH5ZFnZ6d8b+kCa4BCk6qU7WcGDW5HNyUxj0pL3PGJtMrVbI3OtIKJKRqlt86nrLUmH2dQCBHIxVZ1I7mmfsrzr+gVARpCsZx
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

