apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgBZ98b+Pqn9AhD3IpgaKL54FHnlClgMYEbamWW7Ofu4QGIl2Cub0h4ctvVhdPYHGbCUikOZDRKOoc83tJBkx3ZYxZOj1cYOYrtEbZxN7r88lohrZGucxyBjUF5i4vqHSIgoR/G5rGGBYuf+FmLF6ow44ny9iY5Q2G3BMDW1iWlIqLhdXNiFWCVZqcxFuQSf127jMiZlLN9oRG1p+t8weemEj2OGxXbn3RiBTznoRxTRP4awgN37AttXn/FxK0ijjC3LCQMio5X3INTF6W9iAjdw1Sjt4lZL5656r5mZVhuKnuN9hyUYDpkR+pCLYhfJPfxSNBE8YlFgeIisqnGRZb/z8X97hZ0fv9fv9zvz5qezbY+LYL+JI1OgKFtJetK+pLu09BYln824vEqK9PwYiLIH9ZGYcafnAQ1JnSirb5z2Znh4j6GnxlW9p6UmETjqe4D1sH2TOEzHlF+9cR73CLgUxy1TBKgFwA3e7waQUMgWbawX408SGPewoRhjmRB4Xzzm+hkgthgslSW2ul2rTTgF8AObIc0YFcjdRlNNZ57+psewqXG8/AHsEY4RMC+yL/lH6+x7soCIqDpPbDIRVQeRDMId8ahGZXWIvmw47HcNh2HSvgpqNFRUJK0+uYuRD0ISO5dqilRRmdaR7WHfQVvrsToNZLB8vhmFkGBOxHzEg4o6JY4BXSXXL+Krfl2NuhDQyi39J4u/GTVBcte87b5JsNDcjSNeHeLGwKbAaCrX4tcq+8qL9iUP4dIKbsmtmMBqtBLhgd9+ht6aZdvUogCDtDoHmMYvu0PXkjtETkNfDa1u53iH8Iba1wMU9M2EnuEt002GLP9+bbNDi8DRNJer7js1BQ0p4rq7Es9R+WSOjG8H1fp5376I9vCuFNpfWN7DATlbdkWmoSSgg4IU9k8uuI/Q16iV
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

