apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgBMNtp09gazV4/lQlfOvbQAldpiPsWYNGOA1wrTT1UDhZTB9dgvqIWiEeybIW1H5lRCwm9llh9fOOz2SqDk7R/B5VaF9x7b63J7em9jbCu3QcLLxSnrAQZezWuexqjfpZFxY6t+W0e97q4HTIm02LA648I7mNOaNRBTqNuzc2o+Lqepsfb6IcX0hGsyLD4p2mH+q3KEzeY+subZOUpqr6ZcUekDmMy3iHxJ/KCQfNDMr2IiTgbucLkvCcg+uIK0GG5J8s8MMSElv7dhX8uPl3/FB7lDBxhhazcSOBaUCD6yPhj1e2zAwoDmkqxKSz3R18TVRQzAhtFwM/8CfsDhDV2+lWshJappQB5EKhOk2l6nLUIOAFrIdXC2Rqd2SAY2M+O1vjxRU7Gp+j0JhN2VKoI0+S4cKExHRjG/Vl/bSlzQ0oFNPEdlV7owXKScH72VLlKqtQnp9iZ/UddIfMyIucDh3d42wig2FY0bgPnvK/TldP/Dx34H+9ccNT+koxI2wuq96EBf7v3uuil2geSFOJGqR11UKKjXmNC4AAIpDJmFpNioNQWMZQNV9xZfqNNpDLPmcph6oolCos8PVxvX5xo3H2TWx8mIQ0YodOTbAxmi4Q6nBsuuGvqT4kz1oTzCQJkGEIjUbfxlCLHee0lRi92prSocqmk/uuWXQ1Wkta3yZVgY/ywEg6zZjokF7fI7b9yLLmCktGK9G2n5vFIStjMEzV7B0CqBlVlq3e+y+dCFFswlw1oIKh817DQlhkOaJYcBzBQU3HDcuIpOX8nLK/XyBdPb8hwbG4s0x5azGDzC22EwHGtfm6LIczYGMdcDze1fjwDRDTH+RuziBhcpfi9NX5dVymoIOaQRl6ZYmjC7yveHUZh1UfH2rV3iEELH7r6xFfbT0Va4pAlEv0YFgnECy1YV9xxM
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

