apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: ml
spec:
  encryptedData:
    .dockerconfigjson: AgAFHqXWcUB6GgUf5h+NfNwi9ccrxj3Opd8Qg4ulTFeFRWKgnC3bZkSE5q9Z0jEIIcYRS+3lFWe8w4z2slQ4O2txlFzwK8rfyzjJ/tinK4UQySbOco2IRid8850q9205p5WKRzBtlbHfQzvCKdLJgvaRXddPDbjIc5GwWGckKMVRruRL/doqphEyEOA58XDGdqpCa2l8QfB220PB++X/QfkbgKoh2Z7p4yAgNcDtZ06AM3CIl7dGdbQALQuJNwEZkvMaMTlCeTwFtSl8zBliYXsTJA22Z8D2MxyXeSRlG+rVBhYl7XM57RMDpOsObFUWgKXwRS7o6bSkQemcYTsygeBmTKMkCh3Ty7bPcp0bfrR19AYgEnZGEuNmAw3xy54GX46lfVYFOBQrHl4Gun99VkKUDhQD1t7FpBumrtCnzubxn1RrpKjxXPu93BfquNVge0G+j8E4SKu8U2N4Iys/h6+pmLN1th/p8ZEG20fgwVnij03Po+xrUcazMCqKlKWll1GAdWBAiVZRtYYtpBmRD1nNzf14Vv/1XnFKtpD/7Oah6ktaXthMgX0rluc6IMRcRddGZFmwiIQKlcna6oRc1FuCMyFogR/jGvYoAXjoXubQAeRii9l8JzlaJdFWksaBsvBlsHX/BeldAF1zlTmGM3xMB5SzflWDR52EosnfJpqcmtaiKtE7ySkgD+t+aTouOfH+2dOqfJ7DoPz5xmUtA/fHQiCH1H+P/qhqCxvQesReVe0XJD9zhfB+75JLaStJJ1zf8H5EF9NYSoXhVMGSWeZdzrRMRfJZJj7CznBZdQAoh+fZlTtPxFAMxlbh9tbVno+sxPNZ1FxSkmNStgvWV+RhdYeELhO/cNVKHPh6Vx92m0Uy04QcTQMIC7aZ+dIs1FbcQAJ6vLZAUiCskeilHJk8IZgnHPFU
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: ml
    type: kubernetes.io/dockerconfigjson

