apiVersion: v1
kind: Secret
metadata:
  name: storage-secrets
  namespace: ml
type: Opaque
data:
  POSTGRES_USER: bWxmbG93
  POSTGRES_PASSWORD: d2NUaU1uRVc3WnFxSEYyOWNZbFFPekZoNElWblc4VTl2TjJYTlEwN0haaHBveFpQNjY3ZEF3bDV2eEtKMFlrVA==
  MINIO_ACCESS_KEY: bWluYm9ybw==
  MINIO_SECRET_KEY: MTIzbWluYm9ybzEyMw==
  MLFLOW_S3_ENDPOINT_URL: aHR0cDovL21pbmlvLnN0b3JhZ2Uuc3ZjLmNsdXN0ZXIubG9jYWw6OTAwMA==
  POSTGRES_HOST: YWNpZC1taW5pbWFsLWNsdXN0ZXIuc3RvcmFnZS5zdmMuY2x1c3Rlci5sb2NhbA==
