---
# Source: YataiService/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yatai-service-account
  labels:
    app: yatai-service
---
# Source: YataiService/templates/yatai-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: yatai-service
  labels:
    app: yatai-service
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 3000
    targetPort: 3000
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: yatai-service
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
spec:
  template:
    metadata:
      name:  init-db
      labels:
        app: init-postgresdb
    spec:
      containers:
      - image: "docker.io/postgres:13.3"
        name: init-db
        command: ["createdb"]
        args: ["-h","$(POSTGRES_HOST)", "-U", "$(POSTGRES_USER)", "bentoml" ]
        envFrom:
          - secretRef:
              name: storage-secrets
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: storage-secrets
      imagePullSecrets:
        - name: regcred
      restartPolicy: OnFailure
---
# Source: YataiService/templates/yatai-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yatai-service
  labels:
    app: yatai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yatai-service
  template:
    metadata:
      labels:
        app: yatai-service
    spec:
      affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: NotIn
                    values:
                      - kmaster
      imagePullSecrets:
        - name: regcred
      serviceAccountName: yatai-service-account
      containers:
        - name: yatai-service
          image: alvarogg777/arm64v8:nvidia-l4t-base-32.5 # "bentoml/yatai-service:0.8.5"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 50051
          - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          command:
            - "/usr/local/bin/bentoml"
          args:
            - "yatai-service-start"
            - "--repository-type=S3"
            - "--db-url=$(BENTOML_DB_URI)"
            - "--s3-url=s3://bentoml/artifacts"
            - "--s3-endpoint-url=$(S3_ENDPOINT_URL)"
          envFrom:
            - secretRef:
                name: storage-secrets
