---
# Source: YataiService/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yatai-service-account
  labels:
    app: yatai-service
---
# Source: YataiService/templates/yatai-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: yatai-service
  labels:
    app: yatai-service
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 3000
    targetPort: 3000
  - name: grpc
    port: 50051
    targetPort: 50051
  - name: jupyter
    port: 8888
    targetPort: 8888
  - name: dash
    port: 8050
    targetPort: 8050
  - name: flask
    port: 5000
    targetPort: 5000
  selector:
    app: yatai-service
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-bento-db
spec:
  backoffLimit: 12
  template:
    metadata:
      name:  init-bento-db
      labels:
        app: init-postgresdb
    spec:
      containers:
      - image: "docker.io/postgres:13.3"
        name: init-bento-db
        command: ["createdb"]
        # args: ["-h","$(POSTGRES_HOST)", "-U", "$(POSTGRES_USER)", "bentoml" ]
        env:
          - name: TZ   
            value: Europe/Madrid
          - name: PGPASSWORD
            valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: storage-secrets
          - name: PGUSER
            valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: storage-secrets
          - name: PGHOST
            valueFrom:
                secretKeyRef:
                  key: POSTGRES_HOST
                  name: storage-secrets
          - name: PGDATABASE
            value: bentoml
        #envFrom:
        #  - secretRef:
        #      name: storage-secrets
      imagePullSecrets:
        - name: regcred
      restartPolicy: OnFailure
---
# Source: YataiService/templates/yatai-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yatai-service
  labels:
    app: yatai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yatai-service
  template:
    metadata:
      labels:
        app: yatai-service
    spec:
      affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: NotIn
                    values:
                      - kpi4
                      - knode1
      imagePullSecrets:
        - name: regcred
      serviceAccountName: yatai-service-account
      containers:
        - name: yatai-service
          image: alvarogg777/arm64v8:jp46-ml-20220101 # "bentoml/yatai-service:0.8.5"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 50051
          - containerPort: 3000
          - containerPort: 8888
          - containerPort: 8050
          - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          command:
            - "bentoml"
          args:
            - "yatai-service-start"
            - "--repository-type=S3"
            - "--db-url=postgresql://$(PGUSER):$(PGPASSWORD)@$(PGHOST):5432/bentoml"
            - "--s3-url=s3://bentoml/artifacts"
            - "--s3-endpoint-url=$(S3_ENDPOINT_URL)"
          #envFrom:
          #  - secretRef:
          #      name: storage-secrets
          env:
            - name: TZ   
              value: Europe/Madrid
            - name: S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  key: S3_ENDPOINT_URL
                  name: storage-secrets
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: storage-secrets
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: storage-secrets
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_HOST
                  name: storage-secrets
            - name: PGDATABASE
              value: bentoml
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef: 
                  key: MINIO_ACCESS_KEY
                  name: storage-secrets
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef: 
                  key: MINIO_SECRET_KEY
                  name: storage-secrets
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: yatai-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`yatai.k3d.io`)
      kind: Rule
      services:
        - name: yatai-service
          port: 3000
    - kind: Rule
      match: Host(`yatai.k3d.io`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
      - name: yatai-service
        port: 50051
        scheme: h2c
  tls:
    certResolver: default
    options: {}
