---
# Source: YataiService/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yatai-service-account
  labels:
    app: yatai-service
---
# Source: YataiService/templates/yatai-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: yatai-service
  labels:
    app: yatai-service
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 3000
    targetPort: 3000
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: yatai-service
---
# Source: YataiService/templates/yatai-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yatai-service
  labels:
    app: yatai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yatai-service
  template:
    metadata:
      labels:
        app: yatai-service
    spec:
      imagePullSecrets:
        []
      serviceAccountName: yatai-service-account
      securityContext:
        {}
      containers:
        - name: yatai-service
          securityContext:
            null
          image: "bentoml/yatai-service:0.8.5"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 50051
          - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          args:
            {{ if .Values.db_url -}}
            # - "--db-url={{ .Values.db_url }}"
            - "--db-url=$BACKEND_STORE_URI"
            {{- end }}
            {{ if .Values.repo_base_url -}}
            # - "--repo-base-url={{ .Values.repo_base_url}}"
            - "--repo-base-url=$DEFAULT_ARTIFACT_ROOT --s3-endpoint-url=$MLFLOW_S3_ENDPOINT_URL"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ml-secrets
                key: MINIO_ACCESS_KEY
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: ml-secrets
                key: MINIO_SECRET_KEY
          - name: DEFAULT_ARTIFACT_ROOT
            value: s3://yatai/artifacts
          - name: MLFLOW_S3_ENDPOINT_URL
            valueFrom:
              secretKeyRef:
                name: storage-secrets
                key: MINIO_ENDPOINT
          - name: BACKEND_STORE_URI
            valueFrom:
              secretKeyRef:
                name: storage-secrets
                key: backend_store_uri
          resources:
            {}
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
